package three;

@:native("THREE.Geometry") extern class Geometry {
	function new():Void;
	var id : Float;
	var uuid : String;
	var name : String;
	var type : String;
	var vertices : Array<Vector3>;
	var colors : Array<Color>;
	var faces : Array<Face3>;
	var faceVertexUvs : Array<Array<Array<Vector2>>>;
	var morphTargets : Array<MorphTarget>;
	var morphNormals : Array<MorphNormals>;
	var skinWeights : Array<Float>;
	var skinIndices : Array<Float>;
	var lineDistances : Array<Float>;
	var boundingBox : Box3;
	var boundingSphere : BoundingSphere;
	var verticesNeedUpdate : Bool;
	var elementsNeedUpdate : Bool;
	var uvsNeedUpdate : Bool;
	var normalsNeedUpdate : Bool;
	var colorsNeedUpdate : Bool;
	var lineDistancesNeedUpdate : Bool;
	var groupsNeedUpdate : Bool;
	function applyMatrix(matrix:Matrix4):Void;
	function rotateX(angle:Float):Geometry;
	function rotateY(angle:Float):Geometry;
	function rotateZ(angle:Float):Geometry;
	function translate(x:Float, y:Float, z:Float):Geometry;
	function scale(x:Float, y:Float, z:Float):Geometry;
	function lookAt(vector:Vector3):Void;
	function fromBufferGeometry(geometry:BufferGeometry):Geometry;
	function center():Vector3;
	function normalize():Geometry;
	function computeFaceNormals():Void;
	function computeVertexNormals(?areaWeighted:Bool):Void;
	function computeMorphNormals():Void;
	function computeLineDistances():Void;
	function computeBoundingBox():Void;
	function computeBoundingSphere():Void;
	function merge(geometry:Geometry, matrix:Matrix, materialIndexOffset:Float):Void;
	function mergeMesh(mesh:Mesh):Void;
	function mergeVertices():Float;
	function sortFacesByMaterialIndex():Void;
	function toJSON():Dynamic;
	function clone():Geometry;
	function copy(source:Geometry):Geometry;
	function dispose():Void;
	var bones : Array<Bone>;
	var animation : AnimationClip;
	var animations : Array<AnimationClip>;
	function addEventListener(type:String, listener:Dynamic -> Void):Void;
	function hasEventListener(type:String, listener:Dynamic -> Void):Void;
	function removeEventListener(type:String, listener:Dynamic -> Void):Void;
	function dispatchEvent(event:{ var type : String; var target : Dynamic; }):Void;
}